Introduce global configuration file
daisybill/github_workflow pull request #16
Opened 2022-03-04 16:54 UTC by Surzhko

This changes allows to extract main configuration data (all except `user_and_repo`) to global config to home directory

2022-03-06 13:11 UTC, arutinn commented on README.md
> +But all general information except `user_and_repo` could be extracted to global config to home directory with the same name
:+1:

2022-03-06 14:32 UTC, BrianBorge approved these changes
Global config! 🥳 

Thanks for adding this.  I think the next iteration on this should try to remove the requirement from having a config file per project with`user_name_and_repo` entirely.

The reason for this: If I want to make use of the global config, I am required to have at least two config files, one in the user dir and one in the project I am working on.  It would be nice to have one config file, where the project-specific config file acts as an override but is not necessary to include at all.

2022-03-06 14:41 UTC, BrianBorge requested changes

2022-03-06 14:41 UTC, BrianBorge commented on README.md
> +Each repository should contains it's own config (`.github_workflow`), that should looks like:
suggestion (blocking): 
```suggestion
Each repository should contain its own config (`.github_workflow`), which should look like this:
```

2022-03-06 14:41 UTC, BrianBorge commented on README.md
> +But all general information except `user_and_repo` could be extracted to global config to home directory with the same name
suggestion (non-blocking):

```suggestion
Optionally, all general information except `user_and_repo` could be extracted to global config in your home directory with the same name (~./github_workflow)
```

2022-03-06 14:41 UTC, BrianBorge commented on lib/github_workflow/cli.rb
> +    CONFIG_FILE_NAME =".github_workflow".freeze
suggestion(blocking): Add space after constant and space after `=`

```suggestion
    CONFIG_FILE_NAME = ".github_workflow".freeze

```

2022-03-07 11:27 UTC, Surzhko commented on lib/github_workflow/cli.rb
> +    CONFIG_FILE_NAME =".github_workflow".freeze
:facepalm:

2022-03-07 11:29 UTC, Surzhko commented
Yes, I have more ideas how to improve configuration, and go out only to global config with possibility override some project specific options

2022-03-07 13:42 UTC, BrianBorge approved these changes
Looks good.

2022-03-16 12:46 UTC, merged